name: example
description: flutter_html example app.

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter_html:
    path: ..
  flutter:
    sdk: flutter
  wakelock_web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/html5.png
    - assets/mac.svg