name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 2.0.0-nullsafety.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.0

  # Plugins for parsing css
  csslib: ^1.0.0
  css_colors: ^1.1.0

  # Plugins for rendering the <table> tag.
  flutter_layout_grid: ^2.0.5

  # Plugins for rendering the <video> tag.
  video_player: ^2.0.0
  chewie: ^1.0.0

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^4.4.2

  # Plugins for rendering the <audio> tag.
  chewie_audio: ^1.2.0

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^2.0.9

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

